import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  widget1,
  widget2,
}: {
  widget1: React.ReactElement;
  widget2: React.ReactElement;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Super APP</h1>
        {widget1}
        {widget2}
      </body>
    </html>
  );
}
